# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * 2'

jobs:
  build:

    runs-on: ubuntu-latest
    if: >-
      github.event.repository.owner.id == github.event.sender.id ||
      github.event_name == 'schedule'
    steps:
    - uses: actions/checkout@v3
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run .py file
      run: |
        python main.py
    - name: Chickin Api #签到
      run: | 
        echo -n `date +%Y-%m-%d\ %H:%M:%S`\ -\ >> ./run.log 
        tail run.log #避免日志上传失败丢失日志
    - name: Push log #更新日志
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: auto-checkin
        branch: main

 
